name: Deploy SIT

on: 
  workflow_dispatch:
    inputs:
      run_id:
        description: Run-ID 
        required: true
        type: string
      dev_version:
        description: DEV Version
        required: true
        type: string
env:
  SIT_VERSION: ${{ vars.SIT_VERSION }}

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-${{ inputs.run_id }}
          path: dist
          github-token: ${{ github.token }}
          run-id: ${{ inputs.run_id }}

  # Run Tests 

  # Push to SIT
  
  tag_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Tag Commit for SIT 
        run: |
          git checkout ${{input.VERSION}}
          git tag -a SIT-${{ env.VERSION }} -m "CI: ${{ env.VERSION }}"
          git push origin SIT-${{ env.VERSION }}

      - name: Update SIT Version environment variable
        run: | 
          SIT_VERSION=v$(node -p "require('./package.json').version")
          echo "SIT_VERSION=$SIT_VERSION" >> $GITHUB_ENV
