name: Deploy SIT

on: 
  workflow_dispatch:
    tags:
      - '*'

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Tag
        id: vars
        run: |
          echo "BUILD_NUMBER_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Get Run ID
        id: runid
        run: |
          echo "RUN_ID=$(python3 get_run_id.py ${{ env.BUILD_NUMBER_TAG }})" >> $GITHUB_ENV

      - name: test vars
        run: |
          echo ${{ env.BUILD_NUMBER_TAG}}
          echo ${{ env.RUN_ID }}

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_NUMBER_TAG }}
          path: dist
          github-token: ${{ github.token }}
          run-id: ${{ env.RUN_ID }}

      - name: Tag Commit for SIT 
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          echo "$(git --no-pager log --oneline -n 1)"
          git tag -a SIT-${{ env.BUILD_NUMBER_TAG }} -m "CI: SIT-${{ env.BUILD_NUMBER_TAG }}"
          git push origin SIT-${{ env.BUILD_NUMBER_TAG }}

       # Push to SIT
