name: Deploy DEV 

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node Modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          
      - name: Install Dependecies
        run: npm install

      - name: Build Project
        run: npm run build --if-present

      - name: Test Project
        run: npm run test:coverage

      - name: Increment Package Version
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          npm version patch -m "[ci skip] Update to v%s" 
          git push origin main

      - name: Update Version Variable
        run: |
          VERSION=v$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Tag Commit 
        run: |
          git tag -a ${{ env.VERSION }} -m "CI: DEV ${{ env.VERSION }}"
          git push origin ${{ env.VERSION }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.run_id }} 
          path: |
            dist
            !dist/**/*.md
            !dist/test
            !dist/ci

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: dist/test/coverage/lcov-report/index.html


  revision_list:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get Revision List
        run: mkdir -p dist/ci && git --no-pager log --oneline origin/main..HEAD > dist/ci/revision-list.md

      - name: Upload Revision List
        uses: actions/upload-artifact@v4
        with:
          name: revision-list
          path: dist/ci/revision-list.md 

      
