name: Deploy SIT

on: 
  workflow_dispatch:
    inputs:
      run_id:
        description: the ID of the workflow run containing the artifact to deploy
        required: true
        type: string

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-${{ inputs.run_id }}
          path: dist
          github-token: ${{ github.token }}

  # Run Tests 

  # Push to SIT
