name: Deploy SIT

on: 
  workflow_dispatch:
    tags:
      - '*'

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Tag and Run-ID
        id: vars
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "RUN_ID=${GITHUB_RUN_ID}" >> $GITHUB_ENV

      - name: test vars
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.RUN_ID }}

          #  - name: Download Artifacts
          #    uses: actions/download-artifact@v4
          #    with:
          #      name: build-${{ inputs.run_id }}
          #      path: dist
          #      github-token: ${{ github.token }}
          #      run-id: ${{ inputs.run_id }}

  # Run Tests 

  # Push to SIT
  
          # tag_commit:
          #   runs-on: ubuntu-latest
          #   steps:
          #     - name: Tag Commit for SIT 
          #       run: |
          #         git checkout ${{input.VERSION}}
          #         git tag -a SIT-${{ env.VERSION }} -m "CI: ${{ env.VERSION }}"
          #         git push origin SIT-${{ env.VERSION }}

          #     - name: Update SIT Version environment variable
          #       run: | 
          #         curl -L \
          #           -X PATCH \
          #           -H "Accept: application/vnd.github+json" \
          #           -H "Authorization: Bearer ${{ github.token }}"\
          #           -H "X-GitHub-Api-Version: 2022-11-28" \
          #           https://api.github.com/repos/deanwilsondev/pipeline-artifacts/actions/variables/SIT_VERSION\
          #           -d '${{ env.VERSION }}'


